variables:
  SERVICE_NAME: gitlab-contribution-analysis

stages:
  - prepare

image:
  name: node:latest

###
# Jobs
###
setup_node:
  stage: prepare
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
  tags:
    - gitlab-org    

setup_pip:
  stage: prepare
  script:
    - apt-get update 
    - apt-get install python3 -y
  artifacts:
    paths:
      - python_modules/
  tags:
    - gitlab-org    



