variables:
  SERVICE_NAME: gitlab-contribution-analysis

stages:
  - prepare
  - deploy

image:
  name: node:latest

###
# Jobs
###
node_dependencies:
  stage: prepare
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
  tags:
    - gitlab-org    

python_dependencies:
  stage: prepare
  script:
    - apt-get update && apt-get install python3
    - which pip
    - apt install python3-pip
    - pip3 install -r requirements.txt -t ./python_modules/
  artifacts:
    paths:
      - python_modules/
  tags:
    - gitlab-org   

deploy:
  stage: deploy
  script:
    serverless deploy   
  tags:
    - gitlab-org    






